name: Test
on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.12-bookworm
    steps:
      - name: Install dependencies
        run: |
          apt-get update -y
          apt-get install --no-install-recommends -y cmake make git ca-certificates
      - name: Clone
        uses: actions/checkout@v4
      - name: Install Conan
        run: |
          pip install conan==2.3.1
          conan profile detect -f
      - name: Configure without Conan
        run: cmake -B build-without-conan -S . --toolchain toolchain.cmake
      - name: Conan install
        run: >
          conan install .
          -c tools.cmake.cmaketoolchain:user_toolchain="[\"$PWD/toolchain.cmake\"]"
          -c tools.build.cross_building:cross_build=true
      - name: Configure with Conan
        run: cmake --preset conan-release
